### PR TITLE
Which plugins block Firefox users the most, and do those plugins block worse with e10s on?

### PR DESCRIPTION
**Pull request by chutten**
Narrow down the most-reported plugin (Flash20b306) and check to see if it's worse on e10s.

Supporting "Plugin Jank" release criteria work.

### CODE REVIEW

**Comment by vitillo** [comment]
The analysis compares only one specific plugin/version which is likely not enough to make a conclusive statemente for all plugins. What you could do is to run the comparison for the top N plugins where for each plugin you aggregate all its versions.

Why are the other BLOCKED_ON_* probes not included in the analysis?

**Comment by chutten** [comment]
> Why are the other BLOCKED_ON_* probes not included in the analysis?

Mostly it's they aren't part of the [e10s release criteria](https://wiki.mozilla.org/Electrolysis/Release_Criteria/Plugin_Jank). Also, [MODULE_INIT](http://mzl.la/1LOAclB) on e10s only ever reports 0, and I didn't know that [STREAM_INIT](http://mzl.la/1LOA8lC) was a thing until I went looking :S 

I can add them in if you like (though having 100% of responses be 0 really messes up compare_histograms, fyi).

> What you could do is to run the comparison for the top N plugins where for each plugin you aggregate all its versions.

Sure. E10s Release may only care about N = 1 = Flash, but it's sensible to aggregate. What would be the correct way to aggregate these histograms? Sum them, since we're displaying proportions anyway?

**Comment by vitillo** [comment]
If that's the only histogram required for the e10s release criteria then it's fine. To aggregate the histogram you can just sum then.

**Comment by chutten** [comment]
Analysis updated to focus solely on Flash and to aggregate the versions together.

**Comment by vitillo** [comment]
Looks good, thanks. Have you considered running the same analysis for the other top plugins?

**Comment by chutten** [comment]
"other top plugins" HAHAHAHAHAHAHa...oh, you're serious? :D

I hadn't really given it much thought, but I could give it a go... Aggregating the top N plugins... need to develop a method to find those prefixes... What the heck.

**Comment by vitillo** [comment]
I am OK with keeping the analysis as is as long as your goal is to evaluate only Flash; if that's not the case then just looking at Flash is not sufficient.

**Comment by vitillo** [comment]
It's probably worthwhile to check Silverlight just to be on the safe side.

**Comment by chutten** [comment]
I've been told that we really only care about Flash for this... but it would be good to perform due diligence. Especially since the hard part of aggregating the versions has already been written.

**Comment by chutten** [comment]
Alrighty, here's every plugin type that has > 0.1% of responses. (So: Flash, Silverlight, and Java)

Of note is how Silverlight has a non-0 probability of chance. It figures, given how few submissions there were.

**Comment by vitillo** [comment]
Looks good, thanks.

**Pull request merged**
