### PR TITLE
Add experiment for top hang stacks

### PR DESCRIPTION
**Pull request by poiru**
This prints out the top 50 hang stacks and their counts for the e10s and non-e10s populations.

### CODE REVIEW

**Comment by poiru** [comment]
@vitillo Updated to the new template.

**Comment by vitillo** [comment]
This looks good and seems to highlight some differences. Could you add some cells that for both e10s and non-e10s:

- cluster the stacks by their last frame
- compute the percentage of stacks in each cluster wrt the total number of stacks
- print a sorted list of the top 25 clusters (i.e. the last frame) with their relative percentage

**Comment by poiru** [comment]
@vitillo Done, although in a slightly different approach. It prints out the top 25 clusters, but only for e10s. All percentages are in the form `e10s% (non-e10s%)` as requested by Vladan.

**Comment by vitillo** [comment]
You are counting a stack just a single time per hang but there might be multiple hangs that generated the same stack. You can get the number of times a stack generated a hang using the `sum` field of the [histogram](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/docs/main-ping.rst#111).

**Comment by poiru** [comment]
@vitillo Good catch, that made quite a difference.

**Comment by vitillo** [comment]
When I suggested to cluster the stacks by their last frame I didn't meant to remove the previous analysis in which you compared the ratios of the individual stacks between e10s and non-e10s without clustering. We should have both.

**Comment by poiru** [comment]
@vitillo OK, restored those. Also updated this to use the derived dataset.

**Comment by vitillo** [comment]
In our main report we are only considering hangs above 100 ms (see add_gecko_activity). You are summing over every value of the histogram instead. Could you rectify that please?

**Comment by poiru** [comment]
@vitillo Done. As dicussed in IRC, that had no effect for this experiment since we don't yet have the 0 bucket.

**Comment by vitillo** [comment]
Looks good, thanks!

**Pull request merged**
