### PR TITLE
Add week4's analysis for Beta47 A/B experiment.

### PR DESCRIPTION
**Pull request by chutten**
Some changes:
* The dataset is only a week long, from 2016-05-18 to 2016-05-25
* The e10sCohort branch distribution is now reported (instead of just
  enumerating which branches were in the dataset)
* totalTime is used instead of uptime for normalizing rates (totalTime
  is in seconds, so a factor of 60 is applied)
* Windows XP clients are omitted, as they will not be receiving e10s,
  at least to begin.

### CODE REVIEW

**Comment by chutten** [comment]
(( and this time I remembered to change the title ))

**Comment by vitillo** [comment]
* The data is limited to 7 days, I am wondering though if it would make sense to increase the window (to get data from clients with considerable lag) and lower the percentage of clients considered. Given the amount of clients considered the difference in power wouldn't affect us.
* Is `totalTime` collected the same way `uptime` is? Is a monotic clock used for it?

**Comment by vitillo** [comment]
The `notxp` function doesn't seem to be complete. The 64 bit version of Windows XP has 5.2 as version number.

**Comment by chutten** [comment]
`totalTime` is even collected in the same place as `uptime`: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/TelemetrySession.jsm#737

I'm not sure that a sample including clients who haven't pinged in a week is more representative of e10s/!e10s differences than a sample excluding them. A narrow window may even be preferable if we want to lend additional weight to clients running recent beta builds.

I will exclude XP64 as well in `notxp`.

**Comment by chutten** [comment]
As per IRC, there appear to be no XP64 clients on beta (or release), so we can just let that condition slide.

**Comment by vitillo** [comment]
r+

**Pull request merged**
