### PR TITLE
Update e10s_experiment for Beta46apz

### PR DESCRIPTION
**Pull request by chutten**
Needed to switch to using e10sCohort instead of experimentBranch as we are no
longer using experiments to control "experiments".

I also had to introduce some validation around the json.loads as the strings
(especially in the big subset) could be null.

### CODE REVIEW

**Comment by vitillo** [comment]
How often are strings null?

**Comment by vitillo** [comment]
@Uberi Out[17] shouldn't be possible, any ideas?

**Comment by Uberi** [comment]
Re: Out[17], that's now fixed in https://github.com/mozilla/telemetry-batch-view/pull/50.

**Comment by chutten** [comment]
I don't know how often strings are null/None/otherwise invalid. All I know is that the json parser complains on larger samples ( 6 doesn't hit it, 30 seems to) if there is no value, and that the inline conditional gets the analysis past it.

**Comment by vitillo** [comment]
Looks good, there are only a few clients with mismatching e10sEnabled status but they should not impact the analysis.

**Pull request merged**
