### PR TITLE
Add top addons experiment

### PR DESCRIPTION
**Pull request by poiru**
[Bug 1224518](https://bugzilla.mozilla.org/show_bug.cgi?id=1224518)

This experiment lists the top addons in the Telemetry pings and compares them to the [whitelisted e10s addon list](https://wiki.mozilla.org/Electrolysis/Addons). According to jimm, all addons on that page are "approved".

### CODE REVIEW

**Comment by vitillo** [comment]
I am not sure that using the add-on name is good enough. Could you ask in #teamaddons what the best way to match add-ons is?

**Comment by poiru** [comment]
@vitillo I switched to using the addon ID and updated this to use the derived dataset.

**Comment by vitillo** [comment]
s/This experiment lists the top extensions/This analysis lists...

Otherwise it looks good.

**Comment by poiru** [comment]
@vitillo Done.

**Pull request merged**
