### PR TITLE
bug 1226564 - please compare HTTP_*_COMPLETE_LOAD_NET_V2

### PR DESCRIPTION
**Pull request by chutten**
The standard e10s_experiment does not analyse COMPLETE_LOAD_NET_V2 measures.

### CODE REVIEW

**Comment by vitillo** [comment]
Can we add this directly to the `e10s_experiment` notebook? That's going to make it easier to rerun all analyses once new data comes in.

**Comment by chutten** [comment]
Sure. Let me spin up a cluster and I'll update.

**Comment by chutten** [comment]
Alrighty, it's all together now. The only changes are the addition of the two histograms at the bottom and I had to remove MEMORY_HEAP_COMMITTED_UNUSED_RATIO from the analysis because it is no longer in the histograms_definition.

**Comment by vitillo** [comment]
Looks good, thanks!

**Pull request merged**
