### PR TITLE
Add beta analyses

### PR DESCRIPTION
**Pull request by poiru**

### CODE REVIEW

**Comment by vitillo** [comment]
What's this comment about: "# TODO: Fix compare_histograms to work with FX_REFRESH_DRIVER_CHROME_FRAME_DELAY_MS"?

**Comment by poiru** [comment]
@vitillo Sorry, that should've said `FX_REFRESH_DRIVER_CONTENT_FRAME_DELAY_MS`. I'll fix the issue (because its a content process specific metric, `none10s` is empty) and update the PR. I'll also add the extension variants of the analysis.

**Comment by poiru** [comment]
@vitillo Done.

**Comment by poiru** [comment]
@vitillo Done, although I just realized that I left `dataset.filter(dataset.sampleId <= 30)` for the addon analyses. Especially `e10s_with_whitelisted_addons_experiment.ipynb` has a lot less clients that the others. Should I rerun with 100% samples?

**Comment by vitillo** [comment]
Yes, please.

**Pull request merged**
