### PR TITLE
Add parent process thread activity to e10s_top_hang_stacks analysis

### PR DESCRIPTION
**Pull request by poiru**
Child process thread activity is blocked on [bug 1228437](https://bugzilla.mozilla.org/show_bug.cgi?id=1228437).

### CODE REVIEW

**Comment by poiru** [comment]
@vitillo This is pretty much your version. Thanks for your help with this!

**Comment by vitillo** [comment]
@poiru Since the activity histograms of the child process threads are missing, we should plot as well the unnormalized histograms to compare the absolute values.

**Comment by poiru** [comment]
@vitillo Done.

**Comment by vitillo** [comment]
Thanks!

**Pull request merged**
