### PR TITLE
Add SLOW_SCRIPT_PAGE_COUNT for slow script measures

### PR DESCRIPTION
**Pull request by Uberi**
SLOW_SCRIPT_PAGE_COUNT is a better measurement of actual script slowness than SLOW_SCRIPT_NOTICE_COUNT.

We have somewhat less data for SLOW_SCRIPT_PAGE_COUNT compared to SLOW_SCRIPT_NOTICE_COUNT (372 pings vs. 512 pings), which seems to be why the statistical significance is lower.

### CODE REVIEW

**Comment by vitillo** [comment]
You might be able to make the comparison significant by increasing the clientid sampling ratio.

**Comment by Uberi** [comment]
* Use sampleId threshold of 50% to get better statistical significance for the slow script measures.
* Merge master.

**Comment by vitillo** [comment]
As discussed on IRC slow script comparison should use their "own" 50% sampled dataset.

**Comment by vitillo** [comment]
r+

**Pull request merged**
